# Generated by Django 5.1.7 on 2026-07-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0051_loja_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='acao',
            field=models.CharField(choices=[('CRIAR', 'Criou'), ('EDITAR', 'Editou'), ('EXCLUIR', 'Excluiu'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('TRANSFERIR', 'Transferiu estoque'), ('VENDA', 'Venda'), ('CAIXA', 'Caixa'), ('ESTOQUE', 'Estoque'), ('SENHA', 'Senha / usuário'), ('CONFIG', 'Configuração'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20),
        ),
    ]
