# Generated by Django 6.0 on 2026-07-31 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0054_cmv_pagamento_mercadorias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelaMercadoriaAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField(verbose_name='Vencimento')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de agendamento')),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=20)),
                ('observacao', models.CharField(blank=True, default='', max_length=200)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_mercadoria_criadas', to=settings.AUTH_USER_MODEL)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_agendadas', to='app_pdv.entradaestoque')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pdv.loja')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcela_agendada', to='app_pdv.pagamentomercadoria')),
            ],
            options={
                'verbose_name': 'Parcela mercadoria agendada',
                'verbose_name_plural': 'Parcelas mercadoria agendadas',
                'ordering': ['data_vencimento', 'id'],
            },
        ),
    ]
