# Generated by Django 5.1.7 on 2026-09-29 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0062_modulo_fiscal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteEmissaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nfe', 'NF-e (55)'), ('nfce', 'NFC-e (65)'), ('nfse', 'NFS-e'), ('nfse_nacional', 'NFS-e Nacional')], default='nfce', max_length=20)),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('concluido', 'Concluído'), ('parcial', 'Parcial (com erros)'), ('vazio', 'Nenhuma venda processada')], default='processando', max_length=20)),
                ('data_venda_de', models.DateField(blank=True, null=True)),
                ('data_venda_ate', models.DateField(blank=True, null=True)),
                ('pular_ja_emitidas', models.BooleanField(default=True)),
                ('total_solicitado', models.PositiveIntegerField(default=0)),
                ('total_autorizado', models.PositiveIntegerField(default=0)),
                ('total_erro', models.PositiveIntegerField(default=0)),
                ('total_ignorado', models.PositiveIntegerField(default=0)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_emissao_fiscal', to='app_pdv.loja')),
            ],
            options={
                'verbose_name': 'Lote de emissão fiscal',
                'verbose_name_plural': 'Lotes de emissão fiscal',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LoteEmissaoFiscalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('autorizado', 'Autorizado'), ('processando', 'Processando'), ('erro', 'Erro'), ('ignorado', 'Ignorado')], default='pendente', max_length=20)),
                ('mensagem', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lote_emissao_itens', to='app_pdv.documentofiscal')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_pdv.loteemissaofiscal')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lote_emissao_itens', to='app_pdv.venda')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('lote', 'venda'), name='fiscal_lote_item_venda_unica')],
            },
        ),
    ]
