# Generated by Django 5.1.7 on 2026-10-01 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0063_fiscal_lote_emissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscal',
            name='produto_avulso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_fiscais_avulsos', to='app_pdv.produto', verbose_name='Produto (emissão avulsa)'),
        ),
        migrations.AddField(
            model_name='produtodadosfiscais',
            name='aliquota_cofins',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Alíquota COFINS (%)'),
        ),
        migrations.AddField(
            model_name='produtodadosfiscais',
            name='aliquota_icms',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Alíquota ICMS (%)'),
        ),
        migrations.AddField(
            model_name='produtodadosfiscais',
            name='aliquota_pis',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Alíquota PIS (%)'),
        ),
        migrations.AddField(
            model_name='produtodadosfiscais',
            name='cfop_interestadual',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='CFOP interestadual'),
        ),
        migrations.AddField(
            model_name='produtodadosfiscais',
            name='cfop_venda',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='CFOP venda'),
        ),
        migrations.AddField(
            model_name='produtodadosfiscais',
            name='codigo_anp',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='Código ANP'),
        ),
        migrations.AddField(
            model_name='produtodadosfiscais',
            name='codigo_beneficio_fiscal',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cBenef'),
        ),
        migrations.AddField(
            model_name='produtodadosfiscais',
            name='csosn',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='CSOSN (Simples)'),
        ),
        migrations.AddField(
            model_name='produtodadosfiscais',
            name='cst_cofins',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='CST COFINS'),
        ),
        migrations.AddField(
            model_name='produtodadosfiscais',
            name='cst_ibs_cbs',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='CST IBS/CBS (reforma)'),
        ),
        migrations.AddField(
            model_name='produtodadosfiscais',
            name='cst_icms',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='CST ICMS'),
        ),
        migrations.AddField(
            model_name='produtodadosfiscais',
            name='cst_pis',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='CST PIS'),
        ),
        migrations.AddField(
            model_name='produtodadosfiscais',
            name='descricao_anp',
            field=models.CharField(blank=True, default='', max_length=95, verbose_name='Descrição ANP'),
        ),
        migrations.AddField(
            model_name='produtodadosfiscais',
            name='icms_aliquota_ad_rem',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='ICMS alíquota ad rem (R$)'),
        ),
        migrations.AddField(
            model_name='produtodadosfiscais',
            name='pct_glp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='% GLP'),
        ),
        migrations.AddField(
            model_name='produtodadosfiscais',
            name='pct_gn_importado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='% GN importado'),
        ),
        migrations.AddField(
            model_name='produtodadosfiscais',
            name='pct_gn_nacional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='% GN nacional'),
        ),
    ]
