# Generated by Django 5.1.7 on 2026-10-06 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0064_produto_fiscal_avulso'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loteemissaofiscalitem',
            name='fiscal_lote_item_venda_unica',
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='email_contabilidade',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail da contabilidade'),
        ),
        migrations.AddField(
            model_name='fiscalconfig',
            name='whatsapp_contabilidade',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp da contabilidade'),
        ),
        migrations.AddField(
            model_name='loteemissaofiscal',
            name='modo',
            field=models.CharField(choices=[('vendas', 'Vendas PDV'), ('avulso', 'Avulso por produto')], default='vendas', max_length=20),
        ),
        migrations.AddField(
            model_name='loteemissaofiscalitem',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lote_emissao_itens', to='app_pdv.produto'),
        ),
        migrations.AddField(
            model_name='loteemissaofiscalitem',
            name='quantidade_emitida',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loteemissaofiscalitem',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lote_emissao_itens', to='app_pdv.venda'),
        ),
        migrations.AddConstraint(
            model_name='loteemissaofiscalitem',
            constraint=models.UniqueConstraint(condition=models.Q(('venda__isnull', False)), fields=('lote', 'venda'), name='fiscal_lote_item_venda_unica'),
        ),
    ]
