# Generated by Django 5.1.7 on 2026-10-08 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdv', '0065_fiscal_contabilidade_lote_nfe'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturezaOperacaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfop', models.CharField(help_text='Somente dígitos, ex.: 5102', max_length=4)),
                ('descricao', models.CharField(max_length=120)),
                ('tributacao', models.CharField(choices=[('produto', 'Usar tributação do produto / matriz'), ('csosn_102', 'Simples Nacional — CSOSN 102'), ('csosn_500', 'ICMS cobrado anteriormente por ST — CSOSN 500'), ('csosn_400', 'Isento — CSOSN 400'), ('csosn_300', 'Imune — CSOSN 300'), ('nao_tributada', 'Não tributada — CSOSN 400'), ('substituicao', 'Substituição tributária — CSOSN 500')], default='produto', max_length=30)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naturezas_operacao_fiscal', to='app_pdv.loja')),
            ],
            options={
                'verbose_name': 'Natureza da operação fiscal',
                'verbose_name_plural': 'Naturezas da operação fiscal',
                'ordering': ['descricao'],
                'constraints': [models.UniqueConstraint(fields=('loja', 'cfop', 'descricao'), name='fiscal_natureza_loja_cfop_desc')],
            },
        ),
    ]
